### ISSUE TITLE
The cli fails to distinguish the continue call from the new transfer call

### ISSUE THREAD

**Issue by djsatok** [near/rainbow-bridge#431] opened 2020-11-23 22:37 UTC
The CLI call for NEAR->Ethereum transfer
```
node index.js transfer-eth-erc20-from-near --amount '50000000000000000000' --near-sender-account <near-account-sending-dai>  --near-sender-sk ed25519:<secret-key-of-near-account-sending-dai> --eth-receiver-address <eth-address-receiving-dai-with-0x-prefix> --eth-master-sk <eth-private-key-paying-for-gas-without-0x-prefix>
```
is taking lots of time by the architecture of the bridge. That's why this call is expected to continue the transfer if it is initiated and exited. However, this is not working for the following scenario:

1. Send 1 token Ethereum -> NEAR. Wait for the transfer to finish.
2. Send 0.5 tokens NEAR -> Ethereum. Wait for some time, then `Ctrl+C`.
3. Repeat the transfer from the previous point.

In this case CLI starts the new transfer without finishing the previous one (because of sufficient amount of tokens in the account ?).

Example:
* [First transaction](https://explorer.near.org/transactions/5k4f4vMSherJM1m71TgBqngZsVunvie9EFtXFvijvUNF)
* [Second transaction](https://explorer.near.org/transactions/C8McM2vhqvG5u9QPHpt5f1bj5Gfrq8orh6cpfc9qTckG)

**Comment by nearmax** [comment] 2020-11-24 00:24
I can confirm, the continuation of the transfer is no longer working. I noticed that it does not write the special checkpoint file into `~/.rainbow` director which is used to resume the transfer. @frol might know more. Also CC @SkidanovAlex

**Comment by frol** [comment] 2020-11-24 12:34
Well, I know why it works as it works right now:

https://github.com/near/rainbow-bridge/blob/884c55cff8e9dfd85a6418496516e05ff2a4e54c/testing/transfer-eth-erc20/from-near.js#L20

https://github.com/near/rainbow-bridge/blob/884c55cff8e9dfd85a6418496516e05ff2a4e54c/testing/transfer-eth-erc20/from-near.js#L44

There is no `~/.rainbow` in place or even a notion of resume mode since it just generates a new prefix based on the current date as of CLI execution time.

@Kouprin in #416 you introduced this new behavior instead of reusing the same transfer log name. Was it in response to the testing needs? We seem to need to recover the old behavior for regular users. To do that, I propose we introduce a CLI argument to specify the transfer log path, and use that in testing scripts explicitly while using a constant default name by default.

**Comment by frol** [comment] 2020-11-24 14:32
On the second thought, as you can see the `transfer-eth-erc20` is located in the `testing` folder, and overall we are moving towards decoupling token connector into a separate entity from the bridge, thus I propose we move/copy the implementation to a separate CLI for eth20 token connector as a short-term solution, and later we may consider designing some universal tool for transferring any tokens through extensions as we discussed previously.

**Comment by frol** [comment] 2020-11-24 14:35
@djsatok Can you identify the minimal scope of the token connector CLI? Is it only `near-to-eth` and `eth-to-near`? Imagine you want to give the tool to somebody who is not going to run their own bridge, and thus they won't have `rainbow-bridge` pulled/installed.

**Comment by djsatok** [comment] 2020-11-25 00:12
@frol, please take a look at #432. I think the minimum token connector CLI is empty. And minimum bridge CLI has the proof extractors. This would be enough to use bridge. We can build more convenient methods on top of these.

**Comment by djsatok** [comment] 2020-11-30 13:36
CC: @SkidanovAlex

**Closed** 2021-02-04 11:43 UTC
Labels: P1
