### ISSUE TITLE
CI is blocked by failures

### ISSUE THREAD

**Issue by Kouprin** [near/rainbow-bridge#278] opened 2020-08-19 10:39 UTC
I've found there are many different reasons how CI tests fail. I guess it's important to collect CI failures to classify them and found solutions.

1. test ethrelay catchup: `Error: [-32000] Server error: Timeout`
```
  | [2020-08-18T22:51:04Z] + node index.js transfer-eth-erc20-from-near --amount 1 --near-sender-account rainbow_bridge_eth_on_near_prover --near-sender-sk ed25519:3D4YudUQRE39Lc4JHghuB5WM8kbgDDa34mnrEP5DdTApVH81af7e2dWgNPEaiQfdJnZq1CNPp5im4Rg5b733oiMP --eth-receiver-address 0xEC8bE1A5630364292E56D01129E8ee8A9578d7D8
  | [2020-08-18T22:51:04Z] + tee -a /tmp/near2ethtransfer.out
  | [2020-08-18T22:51:05Z] Balance of rainbow_bridge_eth_on_near_prover before burning: 1000
  | [2020-08-18T22:51:05Z] Burning 1 tokens on NEAR blockchain in favor of EC8bE1A5630364292E56D01129E8ee8A9578d7D8.
  | [2020-08-18T22:51:15Z] (node:6087) UnhandledPromiseRejectionWarning: Error: [-32000] Server error: Timeout
  | [2020-08-18T22:51:15Z]     at JsonRpcProvider.sendJsonRpc (/var/lib/buildkite-agent/builds/buildkite-i-033911542a2618949-1/nearprotocol/rainbow-bridge/environment/node_modules/near-api-js/lib/providers/json-rpc-provider.js:145:27)
  | [2020-08-18T22:51:15Z]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
  | [2020-08-18T22:51:15Z]     at async Account.signAndSendTransaction (/var/lib/buildkite-agent/builds/buildkite-i-033911542a2618949-1/nearprotocol/rainbow-bridge/environment/node_modules/near-api-js/lib/account.js:98:22)
  | [2020-08-18T22:51:15Z]     at async Command.execute (/var/lib/buildkite-agent/builds/buildkite-i-033911542a2618949-1/nearprotocol/rainbow-bridge/environment/commands/transfer-eth-erc20-from-near.js:61:20)
  | [2020-08-18T22:51:15Z]     at async Promise.all (index 0)
  | [2020-08-18T22:51:15Z]     at async /var/lib/buildkite-agent/builds/buildkite-i-033911542a2618949-1/nearprotocol/rainbow-bridge/environment/index.js:555:3
  | [2020-08-18T22:51:15Z] (node:6087) UnhandledPromiseRejectionWarning: Unhandled promise rejection.
```

2. test ethrelay catchup `Error: [-32000] Server error: query has timed out`:
```
  | [2020-08-19T07:46:50Z] + node index.js transfer-eth-erc20-from-near --amount 1 --near-sender-account rainbow_bridge_eth_on_near_prover --near-sender-sk ed25519:3D4YudUQRE39Lc4JHghuB5WM8kbgDDa34mnrEP5DdTApVH81af7e2dWgNPEaiQfdJnZq1CNPp5im4Rg5b733oiMP --eth-receiver-address 0xEC8bE1A5630364292E56D01129E8ee8A9578d7D8
  | [2020-08-19T07:46:50Z] + tee -a /tmp/near2ethtransfer.out
  | [2020-08-19T07:46:50Z] Balance of rainbow_bridge_eth_on_near_prover before burning: 1000
  | [2020-08-19T07:46:50Z] Burning 1 tokens on NEAR blockchain in favor of EC8bE1A5630364292E56D01129E8ee8A9578d7D8.
  | [2020-08-19T07:46:53Z] Current light client head is: hash=4v5ewLqurHmLtnQJUoMiXZPTDEmxiGXUK1sCT8KrWmgd, height=383
  | [2020-08-19T07:46:53Z] Block 389 is not available on the light client yet. Current height of light client is 383. Sleeping 10 seconds.
  | [2020-08-19T07:47:03Z] Current light client head is: hash=4v5ewLqurHmLtnQJUoMiXZPTDEmxiGXUK1sCT8KrWmgd, height=383
  | [2020-08-19T07:47:03Z] Block 389 is not available on the light client yet. Current height of light client is 383. Sleeping 10 seconds.
  | [2020-08-19T07:47:13Z] Current light client head is: hash=L16SP33T9GmPUDmXE9ePRxyHmovH2tCUFTend3oNqZd, height=392
  | [2020-08-19T07:47:13Z] Near2EthClient block is at 392 which is further than the needed block 389
  | [2020-08-19T07:47:13Z] Burnt "1"
  | [2020-08-19T07:47:23Z] (node:5940) UnhandledPromiseRejectionWarning: Error: [-32000] Server error: query has timed out
  | [2020-08-19T07:47:23Z]     at JsonRpcProvider.sendJsonRpc (/var/lib/buildkite-agent/builds/buildkite-i-05e2abb1767fdedbe-1/nearprotocol/rainbow-bridge/environment/node_modules/near-api-js/lib/providers/json-rpc-provider.js:145:27)
  | [2020-08-19T07:47:23Z]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
  | [2020-08-19T07:47:23Z]     at async JsonRpcProvider.query (/var/lib/buildkite-agent/builds/buildkite-i-05e2abb1767fdedbe-1/nearprotocol/rainbow-bridge/environment/node_modules/near-api-js/lib/providers/json-rpc-provider.js:65:24)
  | [2020-08-19T07:47:23Z]     at async Account.viewFunction (/var/lib/buildkite-agent/builds/buildkite-i-05e2abb1767fdedbe-1/nearprotocol/rainbow-bridge/environment/node_modules/near-api-js/lib/account.js:244:24)
  | [2020-08-19T07:47:23Z]     at async Command.execute (/var/lib/buildkite-agent/builds/buildkite-i-05e2abb1767fdedbe-1/nearprotocol/rainbow-bridge/environment/commands/transfer-eth-erc20-from-near.js:189:25)
  | [2020-08-19T07:47:23Z]     at async Promise.all (index 0)
  | [2020-08-19T07:47:23Z]     at async /var/lib/buildkite-agent/builds/buildkite-i-05e2abb1767fdedbe-1/nearprotocol/rainbow-bridge/environment/index.js:555:3
```

3. e2e always fails locally at @Kouprin, https://github.com/near/rainbow-bridge/issues/256.
```
Mint failed with error:
Error: {"ActionError":{"index":0,"kind":{"FunctionCallError":{"HostError":{"GuestPanic":{"panic_msg":"panicked at 'Failed to verify the proof', mintable-fungible-token/src/lib.rs:450:9"}}}}}}
    at signAndSendTransaction (/Users/kpr/near/rainbow-bridge/environment/lib/borsh/index.js:308:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async NearMintableToken.value [as mint] (/Users/kpr/near/rainbow-bridge/environment/lib/borsh/index.js:340:39)
    at async Function.mint (/Users/kpr/near/rainbow-bridge/environment/commands/transfer-eth-erc20-to-near.js:144:13)
    at async Command.execute (/Users/kpr/near/rainbow-bridge/environment/commands/transfer-eth-erc20-to-near.js:271:13)
    at async Promise.all (index 0)
    at async /Users/kpr/near/rainbow-bridge/environment/index.js:467:16
```

**Comment by ailisp** [comment] 2020-08-19 16:38
1 and 2 i tracked in #258. And i've fixed 1 in #267 . Also wip to fix 2 in #267 
3. I still don't have an idea

**Comment by ailisp** [comment] 2020-08-19 17:22
Found a serious fail: `query` rpc fails even after 10 retries (wait 500ms first, 1.1^n*500ms for next): https://buildkite.com/nearprotocol/rainbow-bridge/builds/595#aede29a7-50fc-4ff5-a8c1-1653af38cb6c
Is this an issue of nearcore?

**Comment by nearmax** [comment] 2020-08-20 00:07
This is blocking https://github.com/near/rainbow-bridge/pull/275 which is fixing a critical issue. I am going to merge the PR right now and will assign P0 priority to this issue.

**Comment by ailisp** [comment] 2020-08-20 16:42
<img width="874" alt="image" src="https://user-images.githubusercontent.com/13259400/90800236-40b30780-e2c9-11ea-828f-f6bdb3a0c11d.png">
Fixed in #267 dependabot has run ci a few times after that, show ci test is very solid 😂

**Comment by ailisp** [comment] 2020-08-25 17:19
This will not happen after split #315, because we no longer link source code to ~/.rainbow/bridge and there's no clean up happens (buildkite new build will clone repo again into different folder

**Comment by Kouprin** [comment] 2020-08-26 16:04
happens in `ci/test_challenge.sh`
```

[2020-08-26T14:54:09Z] + node index.js transfer-eth-erc20-from-near --amount 1 --near-sender-account rainbow_bridge_eth_on_near_prover --near-sender-sk ed25519:3D4YudUQRE39Lc4JHghuB5WM8kbgDDa34mnrEP5DdTApVH81af7e2dWgNPEaiQfdJnZq1CNPp5im4Rg5b733oiMP --eth-receiver-address 0xEC8bE1A5630364292E56D01129E8ee8A9578d7D8
--
  | [2020-08-26T14:54:09Z] + tee -a /tmp/near2ethtransfer.out
  | [2020-08-26T14:54:10Z] Balance of rainbow_bridge_eth_on_near_prover before burning: 1000
  | [2020-08-26T14:54:10Z] Burning 1 tokens on NEAR blockchain in favor of EC8bE1A5630364292E56D01129E8ee8A9578d7D8.
  | [2020-08-26T14:54:10Z] TxHash 2NxHVpXzYtBFkH9ggVZyrCpmMD71FzrhLbRhh67SuCAj
  | [2020-08-26T14:54:12Z] []
  | [2020-08-26T14:54:12Z] {
  | [2020-08-26T14:54:12Z]   status: { SuccessValue: 'AQAAAAAAAAAAAAAAAAAAAOyL4aVjA2QpLlbQESno7oqVeNfY' },
  | [2020-08-26T14:54:12Z]   transaction: {
  | [2020-08-26T14:54:12Z]     signer_id: 'rainbow_bridge_eth_on_near_prover',
  | [2020-08-26T14:54:12Z]     public_key: 'ed25519:7PGseFbWxvYVgZ89K1uTJKYoKetWs7BJtbyXDzfbAcqX',
  | [2020-08-26T14:54:12Z]     nonce: 4,
  | [2020-08-26T14:54:12Z]     receiver_id: 'nearfuntoken',
  | [2020-08-26T14:54:12Z]     actions: [ [Object] ],
  | [2020-08-26T14:54:12Z]     signature: 'ed25519:24bMXPakZLEreahHL85GnPGq6JjT2zA9RftwpMg7eAhVeWZoMMo8mDLyFviEnd8hkjmuT7f9fYDCk2yEAcMcg4Vv',
  | [2020-08-26T14:54:12Z]     hash: '2NxHVpXzYtBFkH9ggVZyrCpmMD71FzrhLbRhh67SuCAj'
  | [2020-08-26T14:54:12Z]   },
  | [2020-08-26T14:54:12Z]   transaction_outcome: {
  | [2020-08-26T14:54:12Z]     proof: [],
  | [2020-08-26T14:54:12Z]     block_hash: '2f7ZbhnTESA8wLzmmkePDFowmLefD35tAoxmTwzVgbg3',
  | [2020-08-26T14:54:12Z]     id: '2NxHVpXzYtBFkH9ggVZyrCpmMD71FzrhLbRhh67SuCAj',
  | [2020-08-26T14:54:12Z]     outcome: {
  | [2020-08-26T14:54:12Z]       logs: [],
  | [2020-08-26T14:54:12Z]       receipt_ids: [Array],
  | [2020-08-26T14:54:12Z]       gas_burnt: 2428084223182,
  | [2020-08-26T14:54:12Z]       tokens_burnt: '2428084223182000000000',
  | [2020-08-26T14:54:12Z]       executor_id: 'rainbow_bridge_eth_on_near_prover',
  | [2020-08-26T14:54:12Z]       status: [Object]
  | [2020-08-26T14:54:12Z]     }
  | [2020-08-26T14:54:12Z]   },
  | [2020-08-26T14:54:12Z]   receipts_outcome: [
  | [2020-08-26T14:54:12Z]     {
  | [2020-08-26T14:54:12Z]       proof: [],
  | [2020-08-26T14:54:12Z]       block_hash: 'HjXpBazY6q6DQgBBZ23QmVKJp651Kzt2CtBwCrCzXgTg',
  | [2020-08-26T14:54:12Z]       id: 'GAaBWhGu5G6xsahXWejHqLLL8Fv6SCSAQsbQpxx8MRND',
  | [2020-08-26T14:54:12Z]       outcome: [Object]
  | [2020-08-26T14:54:12Z]     },
  | [2020-08-26T14:54:12Z]     {
  | [2020-08-26T14:54:12Z]       proof: [],
  | [2020-08-26T14:54:12Z]       block_hash: '43pFxZmeX1Df3U8Eod3JUF1wwUNU5GqSk8Q5qVVoUyPx',
  | [2020-08-26T14:54:12Z]       id: '8REf8XiMJxGqFa83Luckixec2FMjERRPJBFMkbUj91LC',
  | [2020-08-26T14:54:12Z]       outcome: [Object]
  | [2020-08-26T14:54:12Z]     }
  | [2020-08-26T14:54:12Z]   ]
  | [2020-08-26T14:54:12Z] }
  | [2020-08-26T14:54:12Z] Current light client head is: hash=46bhti5jsG5hnSHe44mrfa4im7vYVRdV3pASr5SctVBr, height=298
  | [2020-08-26T14:54:12Z] Block 620 is not available on the light client yet. Current height of light client is 298. Sleeping 10 seconds.
  | [2020-08-26T14:54:22Z] Current light client head is: hash=46bhti5jsG5hnSHe44mrfa4im7vYVRdV3pASr5SctVBr, height=298
  | [2020-08-26T14:54:22Z] Block 620 is not available on the light client yet. Current height of light client is 298. Sleeping 10 seconds.
  | [2020-08-26T14:54:32Z] Current light client head is: hash=46bhti5jsG5hnSHe44mrfa4im7vYVRdV3pASr5SctVBr, height=298
  | [2020-08-26T14:54:32Z] Block 620 is not available on the light client yet. Current height of light client is 298. Sleeping 10 seconds.
  | [2020-08-26T14:54:42Z] Current light client head is: hash=46bhti5jsG5hnSHe44mrfa4im7vYVRdV3pASr5SctVBr, height=298
  | [2020-08-26T14:54:42Z] Block 620 is not available on the light client yet. Current height of light client is 298. Sleeping 10 seconds.
  | [2020-08-26T14:54:53Z] Current light client head is: hash=46bhti5jsG5hnSHe44mrfa4im7vYVRdV3pASr5SctVBr, height=298
  | [2020-08-26T14:54:53Z] Block 620 is not available on the light client yet. Current height of light client is 298. Sleeping 10 seconds.
  | [2020-08-26T14:55:03Z] Current light client head is: hash=46bhti5jsG5hnSHe44mrfa4im7vYVRdV3pASr5SctVBr, height=298
  | [2020-08-26T14:55:03Z] Block 620 is not available on the light client yet. Current height of light client is 298. Sleeping 10 seconds


```

**Comment by ailisp** [comment] 2020-08-26 16:34
> happens in ci/test_challenge.sh

This is fixed in #323 , as you can see from log, root cause is watch dog didn't start because log folder didn't created synchronously before pm2 launch watch dog.

**Comment by Kouprin** [comment] 2020-09-12 09:28
happens in `test command as installed from npm`

[2020-09-12T09:11:02Z] rainbow-bridge-cli-1.0.12.tgz
--
  | [2020-09-12T09:11:02Z] + rm -rf testenv
  | [2020-09-12T09:11:02Z] + mkdir testenv
  | [2020-09-12T09:11:02Z] + cd testenv
  | [2020-09-12T09:11:02Z] + npm init -y
  | [2020-09-12T09:11:02Z] + npm i /var/lib/buildkite-agent/builds/buildkite-i-0ff76ec97b87c9d4e-1/nearprotocol/rainbow-bridge/ci/../rainbow-bridge-cli-1.0.12.tgz
  | [2020-09-12T09:11:03Z] npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
  | [2020-09-12T09:11:03Z] npm ERR! premature close
  | [2020-09-12T09:11:03Z]
  | [2020-09-12T09:11:03Z] npm ERR! A complete log of this run can be found in:
  | [2020-09-12T09:11:03Z] npm ERR!     /var/lib/buildkite-agent/.npm/_logs/2020-09-12T09_11_03_672Z-debug.log
  | [2020-09-12T09:11:03Z] cp: cannot stat ‘/var/lib/buildkite-agent/.rainbow/logs’: No such file or directory
  | [2020-09-12T09:11:03Z] cp: cannot stat ‘/var/lib/buildkite-agent/.rainbow/logs’: No such file or directory
  | [2020-09-12T09:11:03Z] 🚨 Error: The command exited with status 1

**Comment by Kouprin** [comment] 2020-09-12 09:30
`test command as installed from npm` will be disabled in https://github.com/near/rainbow-bridge-cli/pull/342 until CI is fixed

**Comment by djsatok** [comment] 2021-02-04 12:12
Outdated

**Closed by djsatok** 2021-02-04 12:12 UTC
Labels: P0, discussion, testing
